require("plugins.plugins-setup")

require("core.options")
require("core.keymaps")

require("plugins.lualine")
require("plugins.nvim-tree")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.comment")
require("plugins.autopairs")
require("plugins.bufferline")
require("plugins.toggleterm")
require("plugins.smear-cursor")

require("plugins.noice")
require("plugins.dashboard")
require("plugins.render-markdown")
require("plugins.indent-blankline")
require("plugins.aerial")
require("plugins.gitsigns")
